config/routes.rb
Rails.application.routes.draw do

  get 'orders/show'

  root 'store#shoe'

  post 'orders/create' => 'orders#create'

  get 'watch' => 'store#watch'

  get 'watch01/souhu' => 'store#watch'

  get 'orders/watch_succeed'

  get 'test' => 'store#test'

  devise_for :admins, controllers: {
    sessions: 'admin/sessions'
  }

  get 'admin' => 'admin#index'
  namespace :admin do
    get 'orders' => 'orders#index'
    post 'orders/:id/edit' => 'orders#edit', as: :edit_orders
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/order.rb
class Order < ActiveRecord::Base
  enum status: [:order_new_created, :order_valid, :order_sent, :order_received, :order_invalid, :order_deleted]
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/admin/orders_controller.rb
MAX_COUNT_PER_PAGE = 15

class Admin::OrdersController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!

  def index
    logger.debug params

    if params[:page].nil?
      current_page = 1
    else
      current_page = params[:page].to_i
    end

    if params[:status].nil?
      order_status = -1
    else
      order_status = params[:status].to_i
    end

    where_conds = {}
    if order_status != -1
      where_conds['status'] = order_status
    end
    query = Order
    if where_conds.size != 0
      query = query.where(where_conds)
    end
    orders = query.offset((current_page - 1) * MAX_COUNT_PER_PAGE).limit(MAX_COUNT_PER_PAGE).eager_load(:product)

    orders_total_count = 0
    if where_conds.size != 0
      orders_total_count = Order.where(where_conds).count
    else
      orders_total_count = Order.count
    end

    @orders = orders
    @order_status = order_status

    @orders_total_count = orders_total_count

    page_num = @orders_total_count / MAX_COUNT_PER_PAGE
    page_num += 1 if @orders_total_count % MAX_COUNT_PER_PAGE

    page_start, page_end = pagination(page_num, current_page, 8)

    @page_start = page_start
    @page_end = page_end
    @page_num = page_num
    @current_page = current_page
  end

  def edit
    order_id = params[:id].to_i
    order_status = params[:status].to_i
    order = Order.find(order_id)
    order.status = order_status
    order.save

    render json: {
      status: 1
    }
  end

  private
    def pagination(page_num, current_page, showed_num)
      page_start = 1

      half = showed_num / 2
      if current_page > half
        page_start = current_page - half + 1
      end

      page_end = page_start + showed_num - 1
      if page_end > page_num
        page_end = page_num
      end

      [page_start, page_end]
    end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Devise::SessionsController
	layout 'admin'
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	layout 'admin'
	before_action :authenticate_admin!

	def index
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
  end

  def watch_succeed
  end

  def create
    product_id = params[:product_id].to_i
    product = Product.find(product_id)
    if product_id == 1
      create_shoe_order(product)
    elsif product_id == 2
      create_watch_order(product)
    end
  end

  def create_shoe_order(product)
    color = params[:color]
    size = params[:size].to_i
    count = params[:count].to_i
    receiver_name = params[:receiver_name]
    receiver_phone = params[:receiver_phone]
    receiver_address = params[:receiver_address]

    variants = {
      color: color,
      size: size
    }

    order = Order.new(
      receiver_name: receiver_name,
      receiver_phone: receiver_phone,
      receiver_address: receiver_address,
      product: product,
      count: count,
      variants: JSON.generate(variants))
    order.save

    begin
      OrderMailer.send_email_to_admin.deliver_later      
    rescue Exception => e
      
    end

    render json: {
      status: 1
    }
  end

  def create_watch_order(product)
    color = params[:color]
    size = params[:size].to_i
    count = params[:count].to_i
    receiver_name = params[:receiver_name]
    receiver_phone = params[:receiver_phone]
    receiver_address = params[:receiver_address]

    variants = {
      color: color
    }

    order = Order.new(
      receiver_name: receiver_name,
      receiver_phone: receiver_phone,
      receiver_address: receiver_address,
      product: product,
      count: count,
      variants: JSON.generate(variants))
    order.save

    begin
      OrderMailer.send_email_to_admin.deliver_later      
    rescue Exception => e
    end

    render json: {
      status: 1
    }    
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def shoe
  end

  def watch
    watch = Product.where(name: '手表').first

    @watch = watch
  end

  def test
    
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/admin/orders/index.html.erb
<h1>订单</h1>
<div style="margin-top: 20px;">
  <div>
    <select name="status">
      <option value="-1"<% if @order_status == -1 %> selected="selected"<% end %>>所有状态的订单</option>
      <% for status in Order.statuses %>
      <% if status[0] != 'order_deleted' %>
      <option value="<%= status[1] %>"<% if @order_status == status[1] %> selected="selected"<% end %>><%= t(status[0]) %></option>
      <% end %>
      <% end %>
    </select>
    <button class="btn btn-primary btn-filter-orders" style="margin-left: 10px;">筛选</button>
  </div>
  <div style="margin-top: 5px;">
  总共<span class="order-total-count"><%= @orders_total_count %></span>个订单
  </div>
</div>

<div style="margin-top: 20px;">
  <table id="orders" class="table">
    <thead>
      <tr>
        <td class="col-order">订单</td>
        <td class="col-receiver">收件人</td>
        <td class="col-date">创建时间</td>
      </tr>
    </thead>
    <tbody>

      <% if @orders.length > 0 %>
        <% for order in @orders %>
          <% product = order.product %>
          <% variants = JSON.parse(order.variants) %>
          <% if product.id == 1 %>

          <tr id="order-<%= order.id %>">
            <td class="col-order">
              <div class="row">
                <div class="col-sm-4">
                  <span class="col-name">编号：</span>
                  <span class="col-value"><%= order.id %></span>
                </div>            
                <div class="col-sm-8">
                  <span class="col-name">状态：</span>
                  <span class="col-value col-status" data-status="<%= Order.statuses[order.status] %>"><%= t(order.status) %></span>
                </div>
                <div class="col-sm-4">
                    <span class="col-name">商品：</span>
                    <span class="col-value"><%= product.name %></span>
                </div>
                <div class="col-sm-4">
                    <span class="col-name">数量：</span>
                    <span class="col-value"><%= order.count %></span>
                </div>
                <div class="col-sm-4">
                    <span class="col-name">总价：</span>
                    <span class="col-value"><%= product.price * order.count %></span>
                </div>
                <div class="col-sm-4">
                    <span class="col-name">颜色：</span>
                    <span class="col-value"><%= t(variants['color']) %></span>
                </div>
                <div class="col-sm-4">
                    <span class="col-name">尺寸：</span>
                    <span class="col-value"><%= variants['size'] %></span>
                </div> 
                <div class="col-sm-12 row-actions">
                  <button class="btn-link btn-edit-order">编辑</button>
                </div>
              </div>
            </td>
            <td class="col-receiver">
              <div class="row">
                <div class="col-sm-4">
                    <span class="col-name">姓名：</span>
                    <span class="col-value"><%= order.receiver_name %></span>
                </div>
                <div class="col-sm-8">
                    <span class="col-name">手机号：</span>
                    <span class="col-value"><%= order.receiver_phone %></span>
                </div>
                <div class="col-sm-12">
                    <span class="col-name">地址：</span>
                    <span class="col-value"><%= order.receiver_address %></span>
                </div>
              </div>
            </td>
            <td class="col-date"><%= order.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
          </tr>

          <% elsif product.id == 2 %>

          <tr id="order-<%= order.id %>">
            <td class="col-order">
              <div class="row">
                <div class="col-sm-4">
                  <span class="col-name">编号：</span>
                  <span class="col-value"><%= order.id %></span>
                </div>            
                <div class="col-sm-8">
                  <span class="col-name">状态：</span>
                  <span class="col-value col-status" data-status="<%= Order.statuses[order.status] %>"><%= t(order.status) %></span>
                </div>
                <div class="col-sm-4">
                    <span class="col-name">商品：</span>
                    <span class="col-value"><%= product.name %></span>
                </div>
                <div class="col-sm-4">
                    <span class="col-name">数量：</span>
                    <span class="col-value"><%= order.count %></span>
                </div>
                <div class="col-sm-4">
                    <span class="col-name">总价：</span>
                    <span class="col-value"><%= product.price * order.count %></span>
                </div>
                <div class="col-sm-4">
                    <span class="col-name">颜色：</span>
                    <span class="col-value"><%= t(variants['color']) %></span>
                </div>
                <div class="col-sm-12 row-actions">
                  <button class="btn-link btn-edit-order">编辑</button>
                </div>
              </div>
            </td>
            <td class="col-receiver">
              <div class="row">
                <div class="col-sm-4">
                    <span class="col-name">姓名：</span>
                    <span class="col-value"><%= order.receiver_name %></span>
                </div>
                <div class="col-sm-8">
                    <span class="col-name">手机号：</span>
                    <span class="col-value"><%= order.receiver_phone %></span>
                </div>
                <div class="col-sm-12">
                    <span class="col-name">地址：</span>
                    <span class="col-value"><%= order.receiver_address %></span>
                </div>
              </div>
            </td>
            <td class="col-date"><%= order.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
          </tr>

          <% end %>

        <% end %>
      <% else %>
        <tr><td colspan="3">没有相应的订单</td></tr>
      <% end %>

    </tbody>
    <tfoot>
        <td class="col-order">订单</td>
        <td class="col-receiver">收件人</td>
        <td class="col-date">创建时间</td>
    </tfoot>
  </table>
</div>

<div id="editOrderTemplate" style="display:none;">
  <div>
    <div class="title">编辑</div>
    <div>
      <span class="col-name">状态：</span>
      <select name="status">
        <% for status in Order.statuses %>
          <% if status[0] != 'order_deleted' %>
          <option value="<%= status[1] %>"><%= t(status[0]) %></option>
          <% end %>        
        <% end %>
      </select>
    </div>
    <div class="container-footer">
      <button class="btn btn-cancel">取消</button>
      <div class="container-footer-right">
        <button class="btn btn-primary btn-update-order"><span class="glyphicon glyphicon-refresh spin"></span><span class="normal-text">更新</span><span class="spin-text">更新中...</span></button>
      </div>
    </div>    
  </div>
</div>

<div class="container-pagination text-center">
  <nav>
    <ul class="pagination">

      <% if @current_page == 1 %>
      <li class="disabled">
        <a href="#" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      <% else %>
      <li>
        <a data-page="<%= @current_page - 1 %>" href="#">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      <% end %>

      <% for i in @page_start..@page_end %>
        <% if i == @current_page %>
        <li class="active"><a><%= i %></a></li>
        <% else %>
        <li><a data-page="<%= i %>" href="#"><%= i %></a></li>
        <% end %>
      <% end %>

      <% if @current_page == @page_num %>
      <li class="disabled">
        <a href="#" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      <% else %>
      <li>
        <a data-page="<%= @current_page + 1 %>" href="#"><span aria-hidden="true">&raquo;</span></a>
      </li>
      <% end %>

    </ul>
  </nav>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
<% if msg.is_a?(String) %>
<div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	<%= content_tag :div, msg, :id => "flash_#{name}" %>
</div>
<% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to t('admin.navigation.home'), admin_path, class: 'navbar-brand' %>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<% if admin_signed_in? %>
				<li><%= link_to t('admin.navigation.orders'), admin_orders_path %></li>
				<li><%= link_to t('admin.navigation.sign_out'), destroy_admin_session_path, :method=>'delete' %></li>
				<% else %>
				<li><%= link_to t('admin.navigation.sign_in'), new_admin_session_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>common-projects</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">

	<header>
		<%= render 'layouts/navigation' %>
	</header>
	<main role="main">
		<%= render 'layouts/messages' %>
		<%= yield %>
	</main>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield :javascript_includes %>
  <script src="http://s4.cnzz.com/z_stat.php?id=1259640451&web_id=1259640451" language="JavaScript"></script>
  <%= csrf_meta_tags %>
  <meta charset="utf-8" />
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
</head>
<body class="<%= controller_name %> <%= action_name %>">

<%= yield %>

</body>
</html>

app/views/orders/show.html.erb
<% provide :title, "百变女神官方旗舰店" %>

<div class="container-shoe-header-static">
  <%= image_tag("shoe_header_static.png", class: "shoe-header-static") %>
</div>
<div class="container-order-succeed">
  <div>订购成功！</div>
  <div>订单创建成功，感谢您的购买！</div>
  <div style="margin-top: 30px;">商品预计于三日内由顺丰快递送达，<br/>请保持通讯畅通，祝您生活愉快！</div>
</div>
<div class="container-button-group">
  <%= link_to "再次购买", root_path, class: "btn-buy-again" %>
</div>

app/views/orders/watch_succeed.html.erb
<% provide :title, "TEVISE官方旗舰店" %>

<div class="container-watch-logo">
  <%= image_tag("watch-logo.png") %>
</div>
<div class="container-order-succeed">
  <div>订购成功！</div>
  <div>订单创建成功，感谢您的购买！</div>
  <div style="margin-top: 30px;">商品预计于三日内由顺丰快递送达，<br/>请保持通讯畅通，祝您生活愉快！</div>
</div>
<div class="container-button-group">
  <%= link_to "再次购买", watch_path, class: "btn-buy-again" %>
</div>

app/views/store/shoe.html.erb
<% provide :title, "百变女神官方旗舰店" %>

<div class="container-fixed-bottom">
  <div class="table-row">
    <div class="table-col vertical-middle">
      <a href="#shoeImagesContainer">
        <span>返回顶部</span>
      </a>
    </div>
    <div class="table-col vertical-middle">
      <a href="#orderSection" class="btn-buy-online">
        <span>在线购买</span>
      </a>
    </div>
    <div class="table-col vertical-middle">
      <a href="#orderSection">
        <span>货到付款</span>
      </a>
    </div>
  </div>
</div>

<div id="shoeImagesContainer">
  <div class="container-shoe-header-gif">
    <%= image_tag("shoe_header.gif", class: "shoe-header-gif") %>
  </div>
  <div id="prefaceImageContainer">
    <%= image_tag("shoe_1.jpg", class: "product-page-image") %>
  </div>
  <div class="container-shoe-image-price">
    <%= image_tag("shoe_2.jpg", class: "product-page-image") %>
    <div class="container-btn-buy">
      <a href="#orderSection">
        <%= image_tag("buy-now.png", class: "image-buy-now") %>
      </a>
    </div>
  </div>
  <% for i in 3..14 %>
  <div>
    <%= image_tag("shoe_#{i}.jpg", class: "product-page-image") %>
  </div>
  <% end %>

  <div id="orderSection">
    <div class="order-header">
      <%= image_tag("online-order.png", class: "image-online-order") %>
    </div>
    <div class="order-info">
      <div class="order-info-banner">
        <span class="icons-arrow-down"></span>订单信息
      </div>
      <div class="order-info-body">
        <div class="section-product-variant section-product-variant-color">
          <div class="section-product-variant-title">颜色分类</div>
          <div>
            <span class="variant-option" data-value="silver">银色</span>
            <span class="variant-option" data-value="gold">金色</span>
          </div>
        </div>
        <div class="section-product-variant section-product-variant-size">
          <div class="section-product-variant-title">尺码</div>
          <div>
            <% for i in 35..40 %>
            <label class="variant-option" data-value="<%= i %>" style="padding-left:5px;padding-right:5px;"><span style="opacity:0;">q</span><span><%= i %></span><span style="opacity:0;">q</span></label>
            <% end %>
          </div>

          <div class="row row-standard-size">
            <div class="col-xs-4">标准尺码</div>
            <div class="col-xs-8 col-view-size-helper"><span class="btn" data-toggle="modal" data-target="#sizeHelperPopup">查看尺码助手</span></div>
          </div>
        </div>

        <div class="section-product-variant section-product-variant-count">
          <div class="row">
            <div class="col-xs-4 col-banner">
              <div class="table-row">
                <div class="table-col vertical-middle">
                  <div class="buy-count-banner">购买数量</div>
                </div>
              </div>
            </div>
            <div class="col-xs-8 col-count">
              <span class="btn-minus">-</span>
              <input type="number" value="1" name="productCount" id="productCount" />
              <span class="btn-plus">+</span>
            </div>
          </div>
        </div>

        <div class="section-product-variant section-product-variant-receiver">
          <div class="section-product-variant-title">收件信息</div>
          <div>
            <div class="row">
              <div class="col-xs-5">
                <div class="container-input-box container-input-box-name">
                  <span class="icons-receiver"></span><input type="text" placeholder="收件人" name="receiverName" id="receiverName" /><span>*</span>
                </div>
              </div>
              <div class="col-xs-7">
                <div class="container-input-box container-input-box-phone">
                  <span class="icons-phone"></span><input type="number" placeholder="联系电话" name="receiverPhone" id="receiverPhone" /><span>*</span>
                </div>
              </div>
            </div>
            <div class="row row-address">
              <div class="col-xs-12">
                <div class="container-input-box container-input-box-address">
                  <span class="icons-address"></span><input type="text" placeholder="详细地址" name="receiverAddress" id="receiverAddress" /><span>*</span>
                </div>
              </div>
            </div>            
          </div>

          <div class="row row-services">
            <div class="col-xs-4 col-payment">
              <div><span class="service-name">支付方式</span></div>
              <div><span class="service-value">货到付款</span></div>
            </div>
            <div class="col-xs-4 col-transport">
              <div><span class="service-name">快递公司</span></div>
              <div><span  class="service-value">顺丰快递</span></div>
            </div>
            <div class="col-xs-4 col-giving">
              <div><span class="service-name">赠品领取</span></div>
              <div><span class="service-value">增白神器</span></div>
            </div>            
          </div>
        </div>

        <div class="container-order-price">
          <div>
            总计：<span class="total-price">¥228</span><span style="margin: 0 10px;">/</span>运费：<span class="transport-price">¥0</span>
          </div>
          <div class="container-actual-total-price">
            实付：¥<span class="actual-total-price">228</span>
          </div>
        </div>

        <div class="container-buy-btn">
          <button id="buyBtn">确定提交</button>
        </div>

        <div class="row container-purchase-services">
          <div class="col-xs-4 col-refund">
            <div><%= image_tag("refund.png") %></div>
            <div class="purchase-service-title">七天包退换</div>
          </div>
          <div class="col-xs-4 col-transport-free">
            <div><%= image_tag("transport-free.png") %></div>
            <div class="purchase-service-title">顺丰免运费</div>
          </div>
          <div class="col-xs-4 col-pay-after-receive">
            <div><%= image_tag("pay-after-receive.png") %></div>
            <div class="purchase-service-title">全国货到付款</div>
          </div>                    
        </div>

        <div class="container-icp">
          ICP备案号：浙ICP备16016328号
        </div>

        <div style="text-align:center;font-size:13px;color:#9e9e9e;padding:10px 0;">金华东旭传动设备有限公司</div>
      </div>
    </div>
  </div>  
</div>

<div id="sizeHelperPopup" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content" style="box-shadow: none;border: none;">
      <div class="modal-header " style="text-align: right;border-bottom: none; padding-bottom:0">
       <span data-dismiss="modal" class="icons-close">
       </span>
     </div>
     <div class="modal-body" style="padding-top:5px">
       <div><%= image_tag("size-helper.png", class: "image-size-helper") %></div>
     </div>
   </div>
 </div>
</div>

<div id="inputErrorPopup" class="modal">
  <div class="modal-dialog">
    <div class="modal-content" style="box-shadow: none;border: none;">
     <div class="modal-body">
        <div class="container-icons"><span class="icons-important"></span></div>
        <div class="container-error-message">
        </div>
     </div>
   </div>
 </div>
</div>

<div id="messagePopup" class="modal">
  <div class="modal-dialog">
    <div class="modal-content" style="box-shadow: none;border: none;">
     <div class="modal-body">
     </div>
   </div>
 </div>
</div>

app/views/store/test.html.erb
<div>
  <span class="mysprites-phone original-dimen"></span>
</div>
<div>
  <span class="mysprites-phone half-dimen"></span>
</div>
<div>
  <span class="mysprites-phone test1"></span>
</div>
<div>
  <span class="mysprites-phone test2"></span>
</div>
<div>
  <span class="mysprites-phone test3"></span>
</div>
<div>
  <span class="mysprites-phone test4"></span>
</div>
<div>
  <span class="mysprites-receiver"></span>
</div>
<div>
  <span class="mysprites-address"></span>
</div>